{% set name = "piemmer" %}
{% set version = "1.0.1.dev0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 2a6ad1cc343b95d5b492a85cbe61426f1aecf9e38b4d2b0545785ba1030e9ea8

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - matplotlib
    - numpy
    - pandas
    - pip
    - python
    - scipy
    - skbio
  run:
    - matplotlib
    - numpy
    - pandas
    - python
    - scipy
    - skbio

test:
  imports:
    - piemmer

about:
  home: The package home page
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "A algorithm to simplify the input for principal component analysis"
  doc_url: https://github.com/HWChang/emmer/wiki
  dev_url: https://github.com/HWChang/emmer/

extra:
  recipe-maintainers:
    - HWChang
