{% set version = "0.1.19" %}
{% set github = "https://github.com/acidgenomics/r-acidplyr" %}

package:
  name: r-acidplyr
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 3ff3f31c9a6f3d7cbc3ba860df6aefc13c585e4ec6bda89d202b79e1cda73ff9
  
build:
  number: 0
  noarch: generic

requirements:
  host:
    # Depends:
    - r-base >=4.0
    # Imports:
    - r-acidbase >=0.3.13
    - r-acidcli >=0.1.0
    - r-acidgenerics >=0.5.17
    - r-goalie >=0.5.0
    # Suggests:
    - r-purrr >=0.3.4
  run:
    # Depends:
    - r-base >=4.0
    # Imports:
    - r-acidbase >=0.3.13
    - r-acidcli >=0.1.0
    - r-acidgenerics >=0.5.17
    - r-goalie >=0.5.0
    # Suggests:
    - r-purrr >=0.3.4

test:
  commands:
    - $R -e "library('AcidPlyr')"

about:
  home: https://r.acidgenomics.com/packages/acidplyr/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: A grammar of S4 class data manipulation.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
